### ISSUE TITLE
"Join Game" should take owner-players back to the game page

### ISSUE THREAD

**Issue by amarkpark** [FallGambit/fall_gambit#55]
I just did a db migration to test jg/support_castling branch and reloaded everything and when I clicked on the "Join Game" it told me the game was full.  We can't expect players to remember their game number.  "Join Game" should take the associated players back to the game.  Perhaps if the current player is an ower the button becomes "Re-Join Game" and link_to game_path(game) so that the players can get to the game."  Otherwise please suggest another option.
![screen shot 2015-12-15 at 3 26 45 pm](https://cloud.githubusercontent.com/assets/13741014/11824679/d7944204-a340-11e5-9d32-fb81f5386db8.png)

**Comment by jeffgerlach** [comment]
Should be addressed in #59

**Comment by amarkpark** [comment]
It wasn't, it still showed "Game is Full."  When I then logged out and clicked on the "Watch Game" button I got:
![screen shot 2015-12-20 at 5 31 49 pm](https://cloud.githubusercontent.com/assets/13741014/11920872/9fcfa374-a73f-11e5-9f62-ad0b311ee238.png)

Which I THINK can be remedied by changing line 8 to:
<% if current_user && current_game.user_turn == current_user.id %>
IOW if there IS a user logged in AND their ID is the same as the user turn.  Although the way the elsif is set up I suspect we MAY just be safer removing the "Watch Game" option at this time. Still the fix for the "Join Game" button for a user-owner didn't seem to work.  Someone else should double check this because my database is acting funny and I need to rebuild something.

**Comment by amarkpark** [comment]
I just tried logging in as the OTHER game owner user and got THIS error:
User turn Current turn is neither white or black user!
![screen shot 2015-12-20 at 5 46 12 pm](https://cloud.githubusercontent.com/assets/13741014/11920945/96b9abde-a741-11e5-934a-54368cc1d7bf.png)

There must be something wrong with my DB... I don't think when I joined the game the first time it actually SAVED me as the Black user:
  id: 1
  game_name: fgtest game
  created_at: 2015-12-20 06:19:48.139762000 Z
  updated_at: 2015-12-20 06:19:48.139762000 Z
  user_turn: 
  check_status: 
  white_user_id: 1
  black_user_id:

**Comment by jeffgerlach** [comment]
Seems like this may have been a DB issue. Merging #66 will fix the NoMethodError and make it more clear which games on the index page are your own.

**Comment by amarkpark** [comment]
BTW... VERY NICE WORK with the "Watch Game"/"Your Turn" button on the welcome page. Looks great and works well.  Kudos.
![screen shot 2015-12-30 at 7 04 54 pm](https://cloud.githubusercontent.com/assets/13741014/12059848/e4c92586-af28-11e5-9671-bc006e8e0595.png)
